const BASE=(process.env.E2E_BASE_URL||'http://127.0.0.1:4000').replace(/\/$/,'');
const timeout=Number(process.env.E2E_TIMEOUT_MS||15000);
async function req(path,{token,method='GET',body,expected=[200]}={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(BASE+path,{method,signal:c.signal,headers:{...(token?{authorization:`Bearer ${token}`}:{}) ,...(body!==undefined?{'content-type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();let data={};try{data=text?JSON.parse(text):{};}catch{data={message:text}}if(!expected.includes(r.status))throw new Error(`${method} ${path} -> ${r.status}: ${text.slice(0,300)}`);return data;}finally{clearTimeout(t)}}
const u=s=>`${s}${Date.now().toString(36)}${Math.random().toString(36).slice(2,5)}`.slice(0,20);
const expectStatus=async(path,opts,status)=>{await req(path,{...opts,expected:[status]});};
let failures=[];
try{
 const a=await req('/api/auth/register',{method:'POST',body:{username:u('ra'),displayName:'Remainder A',password:'GlobalMessenger!123'},expected:[201]});
 const b=await req('/api/auth/register',{method:'POST',body:{username:u('rb'),displayName:'Remainder B',password:'GlobalMessenger!123'},expected:[201]});
 const la=await req('/api/auth/login',{method:'POST',body:{username:a.user.username,password:'GlobalMessenger!123'}}); const lb=await req('/api/auth/login',{method:'POST',body:{username:b.user.username,password:'GlobalMessenger!123'}});
 const ta=la.token,tb=lb.token;
 await expectStatus('/api/auth/login',{method:'POST',body:{username:a.user.username,password:'wrong-password'}},401);
 await expectStatus('/api/profile/me',{token:'expired.invalid.token'},401);
 await req('/api/profile/me',{token:ta});
 await req('/api/profile/me',{token:ta,method:'PATCH',body:{displayName:'Remainder A Updated',bio:'Advanced messenger'}});
 await req('/api/privacy/settings',{token:ta,method:'PATCH',body:{privacyLastSeen:'contacts',privacyProfilePhoto:'contacts'}});
 await req('/api/security/2fa/status',{token:ta});
 await req('/api/security/2fa/setup',{token:ta});
 await req('/api/security/login-history',{token:ta});
 await req('/api/account/sessions',{token:ta});
 await req('/api/crypto/identity',{token:ta,method:'PUT',body:{publicKey:{type:'test-key'},version:1}});
 await req('/api/crypto/identity',{token:ta});
 const conv=await req('/api/conversations/direct',{token:ta,method:'POST',body:{userId:b.user.id}});
 const cid=conv.id;
 await req(`/api/conversations/${cid}/crypto-keys`,{token:ta});
 await req(`/api/conversations/${cid}/organization`,{token:ta,method:'PATCH',body:{favorite:true,pinned:true,mutedUntil:null,disappearingSeconds:86400}});
 await req('/api/conversations/organized?filter=favorites',{token:ta});
 await req('/api/conversations/unread',{token:ta});
 await req('/api/media',{token:ta});
 const msg=await req(`/api/conversations/${cid}/messages`,{token:ta,method:'POST',body:{body:'Remainder E2E message',type:'text'},expected:[200,201]});
 const mid=msg.id||msg.message?.id; if(!mid) throw new Error('Could not create test message');
 await req(`/api/messages/${mid}/info`,{token:ta});
 await req('/api/messages/search?q=Remainder',{token:ta});
 await req('/api/messages/bulk-forward',{token:ta,method:'POST',body:{messageIds:[mid],conversationId:cid},expected:[200,201]});
 await req('/api/messages/bulk-delete',{token:ta,method:'POST',body:{messageIds:[mid]}});
 const poll=await req('/api/polls',{token:ta,method:'POST',body:{conversationId:cid,question:'E2E poll?',options:['Yes','No'],multiple:false},expected:[200,201]});
 const pollId=poll?.id||poll?.poll?.id; const optionId=poll?.options?.[0]?.id||poll?.poll?.options?.[0]?.id;
 if(!pollId||!optionId) throw new Error('Poll response did not contain persisted poll/options');
 await req(`/api/polls/${pollId}/vote`,{token:tb,method:'POST',body:{optionIds:[optionId]}});
 await req(`/api/polls/${pollId}`,{token:ta});
 await req('/api/messages/schedule',{token:ta,method:'POST',body:{conversationId:cid,body:'Scheduled E2E message',scheduledAt:new Date(Date.now()+120000).toISOString()},expected:[200,201]});
 const scheduled=await req('/api/messages/scheduled',{token:ta}); if(Array.isArray(scheduled)&&scheduled[0]?.id) await req(`/api/messages/scheduled/${scheduled[0].id}`,{token:ta,method:'DELETE'});
 await req(`/api/conversations/${cid}/disappearing`,{token:ta});
 await req(`/api/conversations/${cid}/disappearing`,{token:ta,method:'PUT',body:{seconds:86400}});
 await req('/api/messages/location',{token:ta,method:'POST',body:{conversationId:cid,latitude:16.5062,longitude:80.6480},expected:[200,201]});
 await req('/api/messages/live-location',{token:ta,method:'POST',body:{conversationId:cid,latitude:16.5062,longitude:80.6480,expiresAt:new Date(Date.now()+3600000).toISOString()},expected:[200,201]});
 await req('/api/messages/contact',{token:ta,method:'POST',body:{conversationId:cid,name:'E2E Contact',phone:'+919999999999'},expected:[200,201]});
 await req('/api/messages/event',{token:ta,method:'POST',body:{conversationId:cid,title:'E2E Event',startsAt:new Date(Date.now()+3600000).toISOString()},expected:[200,201]});
 await req('/api/ai/conversation-summary',{token:ta,method:'POST',body:{conversationId:cid}});
 await req('/api/ai/document-understanding',{token:ta,method:'POST',body:{filename:'e2e.txt',text:'Global Messenger document test'}});
 await req('/api/ai/smart-notifications',{token:ta});
 await req(`/api/security/verification/${b.user.id}`,{token:ta});
 await req(`/api/search/universal?q=${encodeURIComponent('Remainder')}`,{token:ta});
 await req('/api/blocked/'+b.user.id,{token:ta,method:'POST'}); await req('/api/blocked',{token:ta}); await req('/api/blocked/'+b.user.id,{token:ta,method:'DELETE'});
 console.log('PASS: remainder-feature E2E auth-failure/profile/privacy/2FA/sessions/E2EE/organization/messages/bulk/polls/scheduling/rich-messages/AI/search/block');
}catch(e){failures.push(e instanceof Error?e.message:String(e));}
if(failures.length){console.error('FAIL: remainder-feature E2E');failures.forEach(x=>console.error('- '+x));process.exit(1)}
