import { io, Socket } from 'socket.io-client';
const API = import.meta.env.VITE_API_URL ?? 'http://localhost:4000';
let socket: Socket | null = null, pc: RTCPeerConnection | null = null, stream: MediaStream | null = null, callId = '';
let overlay: HTMLDivElement | null = null;
const esc=(s:string)=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]!));
function sock(){if(socket?.connected)return socket;const token=localStorage.getItem('gm_token');if(!token)return null;socket=io(API,{auth:{token},transports:['websocket','polling']});socket.on('call:offer',(d:any)=>incoming(d));socket.on('call:answer',async(d:any)=>{if(d.callId===callId&&pc)await pc.setRemoteDescription(d.answer)});socket.on('call:ice',async(d:any)=>{if(d.callId===callId&&pc&&d.candidate)try{await pc.addIceCandidate(d.candidate)}catch{}});socket.on('call:end',(d:any)=>{if(d.callId===callId)end(false)});socket.on('call:rejected',(d:any)=>{if(d.callId===callId){alert('Call declined');end(false)}});return socket}
function ui(html:string){if(!overlay){overlay=document.createElement('div');overlay.id='gm-feature-overlay';Object.assign(overlay.style,{position:'fixed',inset:'0',zIndex:'99999',display:'flex',alignItems:'center',justifyContent:'center',background:'rgba(0,0,0,.72)',fontFamily:'system-ui'});document.body.appendChild(overlay)}overlay.innerHTML=html;overlay.style.display='flex';return overlay}
function close(){if(overlay)overlay.style.display='none'}
function conversationId(){return document.querySelector<HTMLButtonElement>('.chat-item.selected')?.dataset.conversationId||null}
async function call(kind:'audio'|'video'){const s=sock(),cid=conversationId();if(!s?.connected)return alert('Realtime connection is not ready. Please wait a moment.');if(!cid)return alert('Open a conversation first.');callId=crypto.randomUUID();try{stream=await navigator.mediaDevices.getUserMedia({audio:true,video:kind==='video'});}catch{return alert(`Please allow ${kind==='video'?'camera and microphone':'microphone'} access.`)}pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});stream.getTracks().forEach(t=>pc!.addTrack(t,stream!));pc.onicecandidate=e=>e.candidate&&s.emit('call:ice',{callId,candidate:e.candidate,conversationId:cid});pc.ontrack=e=>{const v=document.getElementById('gm-remote') as HTMLVideoElement|null;if(v)v.srcObject=e.streams[0]};const offer=await pc.createOffer();await pc.setLocalDescription(offer);s.emit('call:offer',{callId,conversationId:cid,kind,offer,fromName:JSON.parse(localStorage.getItem('gm_user')||'{}').displayName});ui(`<div style="background:#111827;color:#fff;padding:28px;border-radius:20px;width:min(90vw,760px);text-align:center"><h2>${kind==='video'?'📹 Video':'📞 Voice'} call</h2><p>Calling…</p><video id="gm-remote" autoplay playsinline style="width:100%;max-height:55vh;background:#000;border-radius:14px"></video><br><button id="gm-end" style="margin-top:14px;padding:12px 28px;border:0;border-radius:999px;background:#ef4444;color:#fff">End call</button></div>`);document.getElementById('gm-end')!.onclick=()=>end(true)}
function incoming(d:any){callId=d.callId;ui(`<div style="background:#111827;color:#fff;padding:28px;border-radius:20px;width:min(90vw,400px);text-align:center"><div style="font-size:48px">${d.kind==='video'?'📹':'📞'}</div><h2>Incoming ${d.kind==='video'?'video':'voice'} call</h2><p>${esc(d.fromName||'Contact')} is calling</p><button id="gm-no" style="padding:12px 20px;margin:8px;border:0;border-radius:999px;background:#ef4444;color:#fff">Decline</button><button id="gm-yes" style="padding:12px 20px;margin:8px;border:0;border-radius:999px;background:#22c55e;color:#fff">Accept</button></div>`);document.getElementById('gm-no')!.onclick=()=>{socket?.emit('call:reject',{callId:d.callId,conversationId:d.conversationId});close()};document.getElementById('gm-yes')!.onclick=()=>accept(d)}
async function accept(d:any){const s=sock();try{stream=await navigator.mediaDevices.getUserMedia({audio:true,video:d.kind==='video'});}catch{return alert('Camera/microphone permission is required.')}pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.google.com:19302'}]});stream.getTracks().forEach(t=>pc!.addTrack(t,stream!));pc.onicecandidate=e=>e.candidate&&s?.emit('call:ice',{callId:d.callId,candidate:e.candidate,conversationId:d.conversationId});pc.ontrack=e=>{const v=document.getElementById('gm-remote') as HTMLVideoElement|null;if(v)v.srcObject=e.streams[0]};await pc.setRemoteDescription(d.offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);s?.emit('call:answer',{callId:d.callId,answer,conversationId:d.conversationId});ui(`<div style="background:#111827;color:#fff;padding:18px;border-radius:20px;width:min(94vw,800px)"><video id="gm-remote" autoplay playsinline style="width:100%;max-height:65vh;background:#000;border-radius:14px"></video><div style="text-align:center"><button id="gm-end" style="margin-top:14px;padding:12px 28px;border:0;border-radius:999px;background:#ef4444;color:#fff">End call</button></div></div>`);document.getElementById('gm-end')!.onclick=()=>end(true)}
function end(notify:boolean){if(notify)socket?.emit('call:end',{callId});stream?.getTracks().forEach(t=>t.stop());pc?.close();stream=null;pc=null;callId='';close()}
function features(){ui(`<div style="background:#111827;color:#fff;padding:26px;border-radius:20px;width:min(90vw,500px)"><h2>✨ Explore features</h2><button id="gm-v" style="display:block;width:100%;padding:14px;margin:8px 0">📹 Video call</button><button id="gm-a" style="display:block;width:100%;padding:14px;margin:8px 0">📞 Voice call</button><button id="gm-f" style="display:block;width:100%;padding:14px;margin:8px 0">📎 File sharing</button><button id="gm-c" style="display:block;width:100%;padding:12px;margin-top:12px">Close</button></div>`);document.getElementById('gm-v')!.onclick=()=>call('video');document.getElementById('gm-a')!.onclick=()=>call('audio');document.getElementById('gm-f')!.onclick=()=>{close();document.querySelector<HTMLInputElement>('input[type=file]')?.click()};document.getElementById('gm-c')!.onclick=close}
function options(){ui(`<div style="background:#111827;color:#fff;padding:24px;border-radius:18px;width:min(90vw,380px)"><h3>Conversation options</h3><button id="gm-info" style="display:block;width:100%;padding:12px;margin:7px 0">👤 Contact info</button><button id="gm-close" style="display:block;width:100%;padding:12px;margin:7px 0">Close</button></div>`);document.getElementById('gm-info')!.onclick=()=>alert('Contact information is shown in this conversation.');document.getElementById('gm-close')!.onclick=close}
document.addEventListener('click',e=>{const t=e.target as HTMLElement;if(t.closest('.top-actions .icon-btn:nth-child(1)'))call('audio');else if(t.closest('.top-actions .icon-btn:nth-child(2)'))call('video');else if(t.closest('.top-actions .icon-btn:nth-child(3)'))options();else if(t.closest('.sidebar-bottom button'))features()});setTimeout(sock,700);
