import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { io, Socket } from 'socket.io-client';
import { MessageCircle, Search, Settings, Users, Send, Smile, Paperclip, Phone, Video, MoreHorizontal, CheckCheck, Globe2, Sparkles, LogOut, Plus, ArrowLeft } from 'lucide-react';
import './styles.css';
import { api, API } from './api';

type User = { id:string; username:string; displayName:string; avatarUrl?:string|null; lastSeenAt?:string };
type Member = { user:User };
type Chat = { id:string; isGroup:boolean; title?:string|null; members:Member[]; messages?:Message[] };
type Message = { id:string; conversationId:string; senderId:string; body:string; createdAt:string; editedAt?:string|null; deletedAt?:string|null; sender?:User };

function initials(name:string){ return name.trim().slice(0,2).toUpperCase(); }
function chatName(c:Chat, me:string){ return c.isGroup ? (c.title || 'Group') : (c.members.find(m=>m.user.id!==me)?.user.displayName || 'Conversation'); }

function App(){
 const [user,setUser]=useState<User|null>(null); const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [displayName,setDisplayName]=useState(''); const [register,setRegister]=useState(false); const [error,setError]=useState('');
 const [chats,setChats]=useState<Chat[]>([]); const [active,setActive]=useState<Chat|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [text,setText]=useState(''); const [query,setQuery]=useState(''); const [results,setResults]=useState<User[]>([]); const [socket,setSocket]=useState<Socket|null>(null); const [typing,setTyping]=useState(false); const [otherTyping,setOtherTyping]=useState(false); const [mobile,setMobile]=useState(false);
 const filtered=useMemo(()=>chats.filter(c=>chatName(c,user?.id||'').toLowerCase().includes(query.toLowerCase())),[chats,query,user]);
 useEffect(()=>{ const token=localStorage.getItem('gm_token'), stored=localStorage.getItem('gm_user'); if(!token||!stored)return; const me=JSON.parse(stored); setUser(me); const s=io(API,{auth:{token}}); s.on('message:new',(m:Message)=>setMessages(prev=>prev.some(x=>x.id===m.id)?prev:[...prev,m])); s.on('message:updated',(m:Message)=>setMessages(prev=>prev.map(x=>x.id===m.id?m:x))); s.on('message:deleted',(d:any)=>setMessages(prev=>prev.map(x=>x.id===d.id?{...x,body:'',deletedAt:d.deletedAt}:x))); s.on('typing',(d:any)=>{if(active?.id===d.conversationId&&d.userId!==me.id)setOtherTyping(!!d.typing)}); setSocket(s); api.conversations().then(setChats).catch(()=>{}); return()=>s.disconnect(); },[]);
 useEffect(()=>{ if(!active||!socket)return; socket.emit('conversation:join',active.id); api.messages(active.id).then(setMessages).catch(()=>{}); api.read(active.id).catch(()=>{}); setMobile(true); },[active?.id,socket]);
 async function search(v:string){setQuery(v); if(v.trim().length<2){setResults([]);return} try{setResults(await api.searchUsers(v))}catch{setResults([])}}
 async function startChat(target:User){try{const c=await api.direct(target.id);setChats(prev=>[c,...prev.filter(x=>x.id!==c.id)]);setActive(c);setResults([]);setQuery('')}catch(e:any){setError(e.message)}}
 function send(){if(!text.trim()||!active||!socket?.connected)return; socket.emit('message:send',{conversationId:active.id,body:text.trim(),clientId:crypto.randomUUID()}); setText(''); socket.emit('typing',{conversationId:active.id,typing:false});}
 function logout(){localStorage.removeItem('gm_token');localStorage.removeItem('gm_user');socket?.disconnect();setUser(null);setChats([]);setActive(null)}
 if(!user)return <Auth register={register} setRegister={setRegister} username={username} setUsername={setUsername} password={password} setPassword={setPassword} displayName={displayName} setDisplayName={setDisplayName} error={error} onSubmit={async(e:any)=>{e.preventDefault();setError('');const url=`${API}/api/auth/${register?'register':'login'}`;try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(register?{username,displayName:displayName||username,password}:{username,password})});const d=await r.json();if(!r.ok)throw new Error(d.message||'Authentication failed');localStorage.setItem('gm_token',d.token);localStorage.setItem('gm_user',JSON.stringify(d.user));setUser(d.user)}catch(e:any){setError(e.message)}}}/>;
 return <div className="shell">
  <aside className={`sidebar ${mobile?'hidden-mobile':''}`}>
   <div className="brand"><div className="brand-icon"><Globe2 size={21}/></div><div><b>Global</b><span>Messenger</span></div></div>
   <div className="profile"><div className="avatar big">{initials(user.displayName)}</div><div className="profile-text"><b>{user.displayName}</b><span>@{user.username}</span></div><button className="icon-btn" onClick={logout} title="Sign out"><LogOut size={18}/></button></div>
   <div className="search"><Search size={17}/><input value={query} onChange={e=>search(e.target.value)} placeholder="Search people or chats"/></div>
   {results.length>0&&<div className="search-results">{results.filter(u=>u.id!==user.id).map(u=><button key={u.id} onClick={()=>startChat(u)}><div className="avatar">{initials(u.displayName)}</div><div><b>{u.displayName}</b><span>@{u.username}</span></div><Plus size={17}/></button>)}</div>}
   <div className="nav"><button className="active"><MessageCircle size={18}/> Chats <span>{chats.length}</span></button><button><Users size={18}/> Contacts</button></div>
   <div className="section-title">CONVERSATIONS</div>
   <div className="chat-list">{filtered.map(c=><button key={c.id} onClick={()=>setActive(c)} className={`chat-item ${active?.id===c.id?'selected':''}`}><div className="avatar c1">{initials(chatName(c,user.id))}</div><div className="chat-copy"><div><b>{chatName(c,user.id)}</b><small>{c.messages?.[0]?new Date(c.messages[0].createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):''}</small></div><p>{c.messages?.[0]?.body||'Start a conversation'}</p></div></button>)}</div>
   {chats.length===0&&<div className="empty-side"><Globe2 size={28}/><p>No conversations yet.</p><span>Search for a person above to start chatting.</span></div>}
   <div className="sidebar-bottom"><button><Sparkles size={17}/> Explore features</button></div>
  </aside>
  <main className={`conversation ${mobile?'show-mobile':''}`}>
   {active?<><header className="topbar"><button className="back-btn" onClick={()=>setMobile(false)}><ArrowLeft size={19}/></button><div className="chat-heading"><div className="avatar c1">{initials(chatName(active,user.id))}</div><div><b>{chatName(active,user.id)}</b><span>{otherTyping?'typing…':'Active conversation'}</span></div></div><div className="top-actions"><button className="icon-btn"><Phone size={19}/></button><button className="icon-btn"><Video size={20}/></button><button className="icon-btn"><MoreHorizontal size={20}/></button></div></header>
   <div className="messages"><div className="day"><span>Messages</span></div>{messages.filter(m=>m.conversationId===active.id).map(m=><Bubble key={m.id} message={m} own={m.senderId===user.id}/>) }{messages.filter(m=>m.conversationId===active.id).length===0&&<div className="welcome"><div className="welcome-icon"><Globe2 size={30}/></div><h2>Start the conversation</h2><p>Send a message to {chatName(active,user.id)}.</p></div>}</div>
   <div className="composer-wrap"><div className="composer"><button className="icon-btn"><Paperclip size={19}/></button><input value={text} onChange={e=>{setText(e.target.value);socket?.emit('typing',{conversationId:active.id,typing:!!e.target.value.trim()})}} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Write a message..."/><button className="icon-btn"><Smile size={20}/></button><button className="send" onClick={send}><Send size={18}/></button></div><small>{socket?.connected?'● Connected securely':'○ Connecting…'} • Global Messenger</small></div></>:<div className="welcome-home"><div className="welcome-icon"><Globe2 size={42}/></div><h1>Global Messenger</h1><p>Search for anyone and start a conversation without borders.</p></div>}
  </main>
 </div>
}
function Bubble({message,own}:{message:Message;own:boolean}){return <div className={`bubble-row ${own?'own':''}`}><div className={`bubble ${message.deletedAt?'deleted':''}`}><p>{message.deletedAt?'Message deleted':message.body}</p><small>{new Date(message.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}{message.editedAt?' · edited':''} {own&&<CheckCheck size={13}/>}</small></div></div>}
function Auth(p:any){return <div className="auth-page"><div className="auth-card"><div className="auth-logo"><Globe2 size={27}/></div><h1>{p.register?'Create your account':'Welcome back'}</h1><p>{p.register?'Join conversations without borders.':'Connect with the world, instantly.'}</p><form onSubmit={p.onSubmit}>{p.register&&<label>Display name<input value={p.displayName} onChange={e=>p.setDisplayName(e.target.value)} placeholder="Your name" required/></label>}<label>Username<input value={p.username} onChange={e=>p.setUsername(e.target.value)} placeholder="your_username" required/></label><label>Password<input type="password" value={p.password} onChange={e=>p.setPassword(e.target.value)} placeholder="At least 8 characters" required/></label>{p.error&&<div className="error">{p.error}</div>}<button className="primary">{p.register?'Create account':'Sign in'}</button></form><button className="switch" onClick={()=>p.setRegister(!p.register)}>{p.register?'Already have an account? Sign in':'New here? Create an account'}</button></div></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
