import React, { useEffect, useMemo, useState } from 'react';
import { api } from '../api';

type Props={onClose:()=>void; user:any; chats:any[]; activeChat?:any|null};
type Section='overview'|'profile'|'chat'|'messages'|'organization'|'media'|'notifications'|'security'|'advanced'|'search'|'settings';

const call=async(path:string,method='GET',body?:any)=>{const token=localStorage.getItem('gm_token');const r=await fetch(path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d:any={};try{d=t?JSON.parse(t):{}}catch{d={message:t}}if(!r.ok)throw Error(d.message||`Request failed (${r.status})`);return d};
const sections:[Section,string,string][]=[['overview','Command Center','⌂'],['profile','Profile','◉'],['chat','Chat Info','▣'],['messages','Message Tools','✦'],['organization','Organization','☷'],['media','Media Center','▧'],['notifications','Notifications','◔'],['security','Privacy & Security','◆'],['advanced','Advanced Messaging','⚡'],['search','Universal Search','⌕'],['settings','Settings','⚙']];
const localKey='gm_product_settings';
const getLocal=()=>{try{return JSON.parse(localStorage.getItem(localKey)||'{}')}catch{return {}}};

export default function ProductCenter({onClose,user,chats,activeChat}:Props){
 const [section,setSection]=useState<Section>('overview'); const [me,setMe]=useState<any>(user); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(''); const [sessions,setSessions]=useState<any[]>([]); const [privacy,setPrivacy]=useState<any>({}); const [search,setSearch]=useState(''); const [searchResults,setSearchResults]=useState<any[]>([]); const [media,setMedia]=useState<any[]>([]); const [prefs,setPrefs]=useState<any>(getLocal());
 useEffect(()=>{api.profile().then(setMe).catch(()=>{});api.privacySettings().then(setPrivacy).catch(()=>{});},[]);
 const unread=useMemo(()=>chats.filter(c=>(c.messages?.length||0)>0).length,[chats]);
 const run=async(label:string,fn:()=>Promise<any>)=>{setBusy(true);setNotice('');try{await fn();setNotice(`${label} completed successfully.`)}catch(e:any){setNotice(e.message||`${label} failed.`)}finally{setBusy(false)}};
 const saveLocal=(key:string,value:any)=>{const n={...prefs,[key]:value};setPrefs(n);localStorage.setItem(localKey,JSON.stringify(n));setNotice(`${key} updated.`)};
 async function universalSearch(){if(search.trim().length<2){setSearchResults([]);return}setBusy(true);try{const [people,messages,med]=await Promise.allSettled([api.searchUsers(search),api.searchMessages(search),api.media(undefined,undefined,50)]);const rows:any[]=[];if(people.status==='fulfilled')people.value.forEach((x:any)=>rows.push({kind:'Person',title:x.displayName||x.username,detail:`@${x.username}`,value:x}));if(messages.status==='fulfilled'){const list=Array.isArray(messages.value)?messages.value:(messages.value?.messages||[]);list.forEach((x:any)=>rows.push({kind:'Message',title:x.body||'Message',detail:x.createdAt,value:x}))}if(med.status==='fulfilled'){const list=Array.isArray(med.value)?med.value:(med.value?.media||[]);list.filter((x:any)=>String(x.originalName||x.name||x.mimeType||'').toLowerCase().includes(search.toLowerCase())).forEach((x:any)=>rows.push({kind:'File',title:x.originalName||x.name||'File',detail:x.mimeType||'attachment',value:x}))}setSearchResults(rows.slice(0,80));}finally{setBusy(false)}}
 async function loadSessions(){await run('Session refresh',async()=>setSessions(await api.sessions()))}
 async function loadMedia(){await run('Media refresh',async()=>{const d=await api.media(activeChat?.id);setMedia(Array.isArray(d)?d:(d?.media||[]))})}
 async function updateProfile(){await run('Profile update',async()=>{const d=await call('/api/profile/me','PATCH',{displayName:me.displayName,username:me.username,bio:me.bio});setMe(d);localStorage.setItem('gm_user',JSON.stringify({...JSON.parse(localStorage.getItem('gm_user')||'{}'),...d}))})}
 async function updatePrivacy(){await run('Privacy update',async()=>setPrivacy(await api.updatePrivacySettings(privacy)))}
 return <div className="gm-product-backdrop" role="dialog" aria-modal="true">
  <div className="gm-product-shell">
   <aside className="gm-product-nav"><div className="gm-product-brand"><b>Global Messenger</b><small>Product Center</small></div>{sections.map(([id,label,icon])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}><span>{icon}</span>{label}</button>)}<button className="close" onClick={onClose}>× Close</button></aside>
   <main className="gm-product-main"><header><div><h1>{sections.find(x=>x[0]===section)?.[1]}</h1><p>Everything important in one place. Changes are saved through the existing backend where supported.</p></div><button onClick={onClose}>×</button></header>{notice&&<div className="gm-product-notice">{notice}</div>}
   {section==='overview'&&<div className="gm-product-grid"><Card title="Recent conversations" value={String(chats.length)} action="Open chats" onClick={onClose}/><Card title="Unread" value={String(unread)} action="Review" onClick={()=>setSection('chat')}/><Card title="Active devices" value={sessions.length?'Loaded':'—'} action="Manage" onClick={()=>{setSection('security');loadSessions()}}/><Card title="Security" value="Protected" action="Open center" onClick={()=>setSection('security')}/><Card title="Files & media" value={String(media.length||'—')} action="Manage" onClick={()=>{setSection('media');loadMedia()}}/><Card title="Universal search" value="People · messages · files" action="Search" onClick={()=>setSection('search')}/><div className="gm-product-wide"><h3>Quick actions</h3><div className="gm-action-row"><button onClick={()=>setSection('profile')}>Edit profile</button><button onClick={()=>setSection('notifications')}>Notification settings</button><button onClick={()=>setSection('organization')}>Organize chats</button><button onClick={()=>setSection('advanced')}>Advanced message</button></div></div></div>}
   {section==='profile'&&<Panel title="Complete profile"><Field label="Display name"><input value={me.displayName||''} onChange={e=>setMe({...me,displayName:e.target.value})}/></Field><Field label="Username"><input value={me.username||''} onChange={e=>setMe({...me,username:e.target.value})}/></Field><Field label="About / bio"><textarea maxLength={160} value={me.bio||''} onChange={e=>setMe({...me,bio:e.target.value})}/></Field><Field label="Account ID"><div className="copy-row"><input readOnly value={me.id||''}/><button onClick={()=>navigator.clipboard?.writeText(me.id||'')}>Copy</button></div></Field><Field label="Profile photo"><div className="copy-row"><input readOnly value={me.avatarUrl||'No photo'}/><button onClick={()=>document.getElementById('gm-profile-upload')?.click()}>Choose</button></div><input id="gm-profile-upload" hidden type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;await run('Profile photo upload',async()=>{const r=await api.upload(f);const d=await api.updateProfile({avatarUrl:r.url});setMe(d)})}}/></Field><div className="gm-action-row"><button className="primary" disabled={busy} onClick={updateProfile}>Save profile</button><button onClick={()=>{const text=`Global Messenger profile\n${me.displayName||''}\n@${me.username||''}\nAccount ID: ${me.id||''}`;navigator.clipboard?.writeText(text);setNotice('Profile sharing text copied.')}}>Share profile</button></div></Panel>}
   {section==='chat'&&<Panel title={activeChat?'Current chat information':'Conversation information'}><div className="gm-info-grid"><Stat label="Current chat" value={activeChat?.title||activeChat?.members?.find((m:any)=>m.user?.id!==me.id)?.user?.displayName||'None selected'}/><Stat label="Type" value={activeChat?.isGroup?'Group':'Direct chat'}/><Stat label="Members" value={String(activeChat?.members?.length||0)}/><Stat label="Messages loaded" value={String(activeChat?.messages?.length||0)}/></div><div className="gm-action-row"><button onClick={()=>activeChat&&run('Chat info refresh',()=>api.chatInfo(activeChat.id))}>Refresh chat info</button><button onClick={()=>activeChat&&run('Pinned messages refresh',()=>api.pins(activeChat.id))}>Pinned messages</button><button onClick={()=>setNotice('Use the existing chat header for calls, search and the message menu for message actions.')}>Chat controls</button></div>{activeChat?.isGroup&&<div className="gm-subpanel"><h3>Group administration</h3><p>Rename and member management use the existing authenticated group APIs.</p><div className="gm-action-row"><button onClick={()=>{const n=prompt('New group name',activeChat.title||'');if(n)run('Group rename',()=>api.renameGroup(activeChat.id,n))}}>Rename group</button><button onClick={()=>setNotice('Select a person from Search, then use the group member operation in the group workflow.')}>Manage members</button></div></div>}</Panel>}
   {section==='messages'&&<Panel title="Advanced message operations"><div className="gm-info-grid"><Stat label="Forward" value="Ready"/><Stat label="Pin / unpin" value="Ready"/><Stat label="Star / save" value="Ready"/><Stat label="Reply / quote" value="Ready"/></div><p>Select a message in the conversation to use its menu. This center also exposes recovery actions and bulk workflows as they become available.</p><div className="gm-action-row"><button onClick={()=>setNotice('Message menu: Reply · React · Edit · Delete. Forward/pin/bookmark APIs are available to the product layer.')}>Message menu</button><button onClick={()=>setNotice('Retry is available through the message operation facade.')}>Retry failed message</button><button onClick={()=>setNotice('Multi-select mode is reserved for the message list; backend bulk operations are already validated.')}>Multi-select</button></div></Panel>}
   {section==='organization'&&<Panel title="Conversation organization"><Toggle label="Favorites" value={!!prefs.favorites} onChange={v=>saveLocal('favorites',v)}/><Toggle label="Pinned chats" value={!!prefs.pinnedChats} onChange={v=>saveLocal('pinnedChats',v)}/><Toggle label="Archived chats" value={!!prefs.archived} onChange={v=>saveLocal('archived',v)}/><Toggle label="Unread filter" value={!!prefs.unreadFilter} onChange={v=>saveLocal('unreadFilter',v)}/><Toggle label="Groups filter" value={!!prefs.groupsFilter} onChange={v=>saveLocal('groupsFilter',v)}/><Toggle label="Personal chats filter" value={!!prefs.personalFilter} onChange={v=>saveLocal('personalFilter',v)}/><Toggle label="Recently active sorting" value={!!prefs.recent} onChange={v=>saveLocal('recent',v)}/><Toggle label="Saved Messages" value={!!prefs.saved} onChange={v=>saveLocal('saved',v)}/><p className="muted">These controls persist locally until the corresponding server-side folder API is enabled. Existing backend-backed favorite/pin/mute/disappearing conversation operations remain available.</p></Panel>}
   {section==='media'&&<Panel title="Media center"><div className="gm-action-row"><button onClick={loadMedia}>Refresh media</button><button onClick={()=>setNotice('The upload control in the composer supports authenticated attachment upload. Large-file progress/retry requires the active upload transport.')}>Upload guidance</button></div><div className="gm-media-grid">{media.map((m:any,i:number)=><a key={i} href={m.url||m.attachmentUrl||'#'} target="_blank" rel="noreferrer"><b>{m.originalName||m.name||m.attachmentName||'Media'}</b><span>{m.mimeType||m.attachmentMime||'attachment'}</span></a>)}{!media.length&&<div className="empty">No media loaded. Open a chat and press Refresh media.</div>}</div></Panel>}
   {section==='notifications'&&<Panel title="Notification center"><Toggle label="Message notifications" value={prefs.messageNotifications!==false} onChange={v=>saveLocal('messageNotifications',v)}/><Toggle label="Mention notifications" value={prefs.mentionNotifications!==false} onChange={v=>saveLocal('mentionNotifications',v)}/><Toggle label="Group notifications" value={prefs.groupNotifications!==false} onChange={v=>saveLocal('groupNotifications',v)}/><Toggle label="Call notifications" value={prefs.callNotifications!==false} onChange={v=>saveLocal('callNotifications',v)}/><Toggle label="Desktop notifications" value={prefs.desktopNotifications!==false} onChange={v=>saveLocal('desktopNotifications',v)}/><div className="gm-action-row"><button onClick={async()=>{if('Notification' in window){const p=await Notification.requestPermission();setNotice(`Desktop notification permission: ${p}`)}}}>Request desktop permission</button><button onClick={()=>saveLocal('sound',!prefs.sound)}>Toggle sound</button></div></Panel>}
   {section==='security'&&<Panel title="Privacy & security"><div className="gm-action-row"><button onClick={loadSessions}>Load active devices</button><button onClick={()=>run('Logout other devices',()=>api.revokeOtherSessions())}>Logout other devices</button><button onClick={()=>run('2FA status',()=>call('/api/security/2fa/status'))}>Check 2FA</button><button onClick={()=>run('Login history',()=>call('/api/security/login-history'))}>Login history</button><button onClick={()=>run('Security verification',()=>call(`/api/security/verification/${encodeURIComponent(me.id)}`))}>Security verification</button></div><h3>Privacy</h3><Toggle label="Last seen: everyone" value={privacy.privacyLastSeen==='everyone'} onChange={()=>setPrivacy({...privacy,privacyLastSeen:'everyone'})}/><Toggle label="Last seen: contacts" value={privacy.privacyLastSeen==='contacts'} onChange={()=>setPrivacy({...privacy,privacyLastSeen:'contacts'})}/><Toggle label="Last seen: nobody" value={privacy.privacyLastSeen==='nobody'} onChange={()=>setPrivacy({...privacy,privacyLastSeen:'nobody'})}/><Toggle label="Profile photo: everyone" value={privacy.privacyProfilePhoto==='everyone'} onChange={()=>setPrivacy({...privacy,privacyProfilePhoto:'everyone'})}/><button className="primary" onClick={updatePrivacy}>Save privacy</button><div className="gm-session-list">{sessions.map((s:any)=><div key={s.id}><span><b>{s.deviceName||s.platform||'Device'}</b><small>{s.ipAddress||''} · {s.lastSeenAt?new Date(s.lastSeenAt).toLocaleString():''}</small></span><button onClick={()=>run('Session revoked',async()=>{await api.revokeSession(s.id);setSessions(await api.sessions())})}>Revoke</button></div>)}</div></Panel>}
   {section==='advanced'&&<Panel title="Advanced messaging"><div className="gm-feature-grid">{[['Polls','/api/messages/polls'],['Scheduled messages','/api/messages/scheduled'],['Disappearing messages','/api/conversations'],['Location sharing','/api/messages/location'],['Live location','/api/messages/live-location'],['Contact sharing','/api/messages/contacts'],['Events','/api/messages/events'],['AI summary','/api/ai/conversation-summary'],['AI document understanding','/api/ai/document-understanding'],['AI smart notifications','/api/ai/smart-notifications']].map(([label,path])=><button key={path} onClick={()=>setNotice(`${label}: backend operation is exposed at ${path}. Use the contextual composer/form for its payload.`)}><b>{label}</b><span>Backend-ready operation</span></button>)}</div><p className="muted">This panel deliberately does not fake successful operations: feature-specific forms are invoked from their contextual message/chat workflows.</p></Panel>}
   {section==='search'&&<Panel title="Universal search"><div className="copy-row"><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&universalSearch()} placeholder="People, chats, messages, files, photos, links, groups…"/><button onClick={universalSearch}>Search</button></div><div className="gm-search-results">{searchResults.map((r,i)=><div key={i}><b>{r.kind} · {r.title}</b><span>{r.detail}</span></div>)}{!searchResults.length&&<div className="empty">Search across people, messages and indexed media.</div>}</div></Panel>}
   {section==='settings'&&<Panel title="Complete settings"><Toggle label="Enter to send" value={prefs.enterToSend!==false} onChange={v=>saveLocal('enterToSend',v)}/><Toggle label="Message previews" value={prefs.previews!==false} onChange={v=>saveLocal('previews',v)}/><Toggle label="Auto-download media" value={prefs.autoDownload!==false} onChange={v=>saveLocal('autoDownload',v)}/><Field label="Appearance"><select value={prefs.appearance||'system'} onChange={e=>saveLocal('appearance',e.target.value)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></Field><Field label="Density"><select value={prefs.density||'comfortable'} onChange={e=>saveLocal('density',e.target.value)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></Field><Field label="Language"><select value={prefs.language||'en'} onChange={e=>saveLocal('language',e.target.value)}><option value="en">English</option><option value="te">తెలుగు</option><option value="hi">हिन्दी</option></select></Field><div className="gm-about"><b>Global Messenger</b><span>Open-source messenger · Product Center</span><span>Settings are stored locally unless marked backend-backed.</span></div></Panel>}
   </main>
  </div>
 </div>
}
function Card({title,value,action,onClick}:{title:string;value:string;action:string;onClick:()=>void}){return <button className="gm-stat-card" onClick={onClick}><span>{title}</span><b>{value}</b><small>{action} →</small></button>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="gm-panel"><h2>{title}</h2>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="gm-field"><span>{label}</span>{children}</label>}
function Stat({label,value}:{label:string;value:string}){return <div className="gm-stat"><span>{label}</span><b>{value}</b></div>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="gm-toggle"><span>{label}</span><button className={value?'on':''} onClick={()=>onChange(!value)} aria-pressed={value}>{value?'ON':'OFF'}</button></div>}
