export type ProductPhase = 1 | 2 | 3 | 4 | 5;
export type ProductFeature = { id: string; phase: ProductPhase; title: string; category: string; items: string[]; status: 'active' | 'foundation' | 'next'; };

export const PRODUCT_ROADMAP: ProductFeature[] = [
  { id:'profile', phase:1, category:'Profile', title:'Complete Profile Center', status:'foundation', items:['Change profile photo','Display name','Username','About / bio','Online-status controls','Last-seen controls','Profile preview','QR/profile sharing','Copy username','Account ID'] },
  { id:'chat-info', phase:1, category:'Chats', title:'Complete Chat Info', status:'foundation', items:['Contact profile','Media','Files','Links','Starred messages','Pinned messages','Search in conversation','Notifications','Disappearing messages','Block','Report','Clear chat','Delete chat','Group photo','Group description','Members','Admin controls','Add/remove members','Promote/demote admin','Group permissions','Invite link','Leave group'] },
  { id:'message-operations', phase:1, category:'Messages', title:'Advanced Message Menu', status:'foundation', items:['Forward','Copy','Star/save','Pin','Quote','Multi-select','Bulk delete','Bulk forward','Message info','Delivered/read timestamps','Retry failed message','Save/download/share attachment','Link preview','Reply preview','Edited indicator'] },
  { id:'organization', phase:1, category:'Chats', title:'Conversation Organization', status:'foundation', items:['Favorites','Pinned chats','Archive','Unread filter','Groups filter','Personal filter','Custom folders','Mute indicators','Unread badges','Sorting','Recently active','Saved Messages'] },
  { id:'media', phase:1, category:'Media', title:'Complete Media Center', status:'foundation', items:['Full-screen image viewer','Image gallery','Video player','Audio player','Voice messages','Document preview','Media grid','Files tab','Links tab','Download/share','Image compression','Upload progress','Download progress'] },
  { id:'notifications', phase:1, category:'Notifications', title:'Notification Center', status:'foundation', items:['Message notifications','Mention notifications','Group notifications','Call notifications','Friend/request notifications','Notification history','Per-chat settings','Global settings','Sound selection','Desktop controls'] },
  { id:'security', phase:2, category:'Security', title:'Privacy & Security Center', status:'foundation', items:['Active sessions/devices','Logout other devices','Login history','Change password','Two-factor authentication','Passkeys','App PIN','Android biometric lock','Screen-lock behavior','Privacy controls','Blocked users','Security verification','Encryption status','Key/device management'] },
  { id:'advanced-messaging', phase:3, category:'Advanced Messaging', title:'Advanced Messaging', status:'next', items:['Voice notes','Polls','Scheduled messages','Disappearing messages','Message reminders','Auto-delete','Live location','Location sharing','Contact sharing','Calendar/events','Link previews','Advanced media handling','Audio player','Video player','Document preview'] },
  { id:'calls', phase:4, category:'Calls', title:'Advanced Calls', status:'foundation', items:['Incoming-call UI','Outgoing-call UI','Accept/reject','Mute','Speaker','Camera control','Screen sharing','Call duration','Call history','Missed calls','Group calls','Call notifications'] },
  { id:'ai', phase:5, category:'AI', title:'AI Workspace', status:'foundation', items:['AI rewrite','AI translation','AI reply suggestions','AI conversation summary','AI message search','AI chat assistant','AI file/document understanding','AI voice transcription','AI smart notifications'] },
  { id:'search', phase:1, category:'Search', title:'Universal Search', status:'foundation', items:['People','Chats','Messages','Files','Photos','Links','Groups','Sender filter','Date filter','Type filter','Attachment/link filters'] },
  { id:'command-center', phase:1, category:'Dashboard', title:'Command Center', status:'foundation', items:['Recent conversations','Unread messages','Calls','Groups','Saved messages','Files','AI assistant','Security status','Active devices','Quick actions'] },
  { id:'settings', phase:1, category:'Settings', title:'Complete Settings', status:'foundation', items:['Account','Privacy','Security','Notifications','Appearance','Chat','Storage','Language','About','Open source','Privacy policy','Terms','Help center'] }
];

export const PHASE_LABELS: Record<ProductPhase,string> = { 1:'Core product completeness', 2:'Privacy & security', 3:'Advanced messaging', 4:'Advanced calls', 5:'AI' };
